### ISSUE TITLE
watch command broken

### ISSUE THREAD

**Issue by ffinkbe** [unixorn/zsh-quickstart-kit#104]
My `watch` command is broken when using this kit.
It flashes very quickly and is impossible to read.
 
Do you have similar issues? 
Any ideas whats causing this?

**Comment by jfmcdowell** [comment]
@ffinkbe could you explain in greater detail the problems that you are seeing. What command were you running with `watch` and what argeuments ? 

For what its worth, I just ran a test following this procedure:
1. run the command `watch 3 ls`
2. Open a new terminal window
3. `touch test1.txt` and verify output from the next `ls` call
4. `touch test2.txt` and verify output from the next `ls` call

I didn't experience any of the behavior you mentioned until I ran `watch` without the time argument.

**Comment by deadc** [comment]
The problem comes from watch function in `.zsh_functions`

- https://github.com/unixorn/zsh-quickstart-kit/blob/main/zsh/.zsh_functions#L69-L70

Where the parameters end up conflicting with the procps binary.

actually I didn't quite understand what this function is for, since in most linux distributions the watch binary comes by default.

Any limitations regarding MacOS users?

**Comment by unixorn** [comment]
I'll update so it only is defined if there isn't already a `watch` in the user's path. Good catch, @deadc. That's what I get for testing on macOS.
